[package]
name = "lush"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
promkit = "0.1.2"
rlua = "0.19.7"
whoami = "1.4.1"
