[package]
name = "lush"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
promkit = "0.1.2"
rlua = { version = "0.19.7", default-features = false, features = ["system-lua54"] }
whoami = "1.4.1"
